### ISSUE TITLE
Can't play beatmaps

### ISSUE THREAD

**Issue by Loreos7** [Flutterish/Solosu#1]
https://user-images.githubusercontent.com/86934170/184364704-1d2fae24-7627-4b6c-9c9a-bd70c18692e5.mp4

**Comment by WiseDragoon5374** [comment]
Most likely this is because the ruleset hasn't been updated for a while, and lazer updates can break existing rulesets. Wait for them to push out a new update.

**Comment by Flutterish** [comment]
fixed
